services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: emc_lab
      POSTGRES_PASSWORD: emc_lab
      POSTGRES_DB: bookshop
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"
volumes:
  pgdata: