spring.datasource.url=jdbc:postgresql://localhost:5431/bookshop
spring.datasource.username=emc_lab
spring.datasource.password=emc_lab

spring.jpa.hibernate.ddl-auto=validate

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE